---
title: "Homework 1"
author: "Rangel Plachkov"
date: "18/04/2024"
output: pdf_document

---

Task 1
```{r , eval=TRUE}
correctVar <- 0

simulation <- function() {
  vector <- c(rep("good_apples", 20), rep("bad_apples", 4))

  permuted_vector <- sample(vector)

  count_var1 <- sum(permuted_vector[1:6] == "bad_apples")
  count_var2 <- sum(permuted_vector[7:12] == "bad_apples")
  count_var3 <- sum(permuted_vector[13:18] == "bad_apples")
  count_var4 <- sum(permuted_vector[19:24] == "bad_apples")

  if(count_var1 == 1 && count_var2 == 1 && count_var3 == 1 && count_var4 == 1) {
    correctVar <<- correctVar + 1
  }
}

NumRep <- 50000
replicate(NumRep, simulation())

print(correctVar/NumRep)
```

Task 2

```{r , eval=TRUE}
N <- 30

sum_rexp <- function(N) {
    lambda <- 1/5
    rexp_values <- rexp(N, lambda)
    sum_values <- sum(rexp_values)
    result <- sum_values/N
    return(result)
}
F <- function(t){
    count <- sum(vector <= t)
    return(count/num_iterations)
}

num_iterations <- 10000
vector <- replicate(num_iterations, sum_rexp(N))

t_values <- seq(2, 8, by = 00.1)

F_values <- sapply(t_values, F)
plot(t_values, F_values, type = "l", main = "N = 30" ,
    col = "red", 
    xlab = "t", ylab = "F(t) //// pnorm(t, 5, 5 / sqrt(N))")


p_values <- pnorm(t_values, 5, 5 / sqrt(N))

lines(t_values, p_values, col = "blue")
```